### PR TITLE
Update `destination` sample: Quote object keys

### PR DESCRIPTION
**Pull request by PierreFritsch**
The current example led to an issue during `JSON.parse` on my side ("unexpected character n at position 3") -- adding quotes solved the issue on my side.

### CODE REVIEW

**Comment by PierreFritsch** [comment]
More specifically, the error we got was:

> (env-destination-accessor) Error in parsing the destinations from the environment variable.

**Comment by PierreFritsch** [comment]
... thrown by

https://github.com/SAP/cloud-sdk-js/blob/e19ecf19aa28c763ed24114496fa0bace4f76860/packages/core/src/connectivity/scp-cf/destination/destination-from-env.ts#L33

**Comment by artemkovalyov** [comment]
Thanks, @PierreFritsch ,

I assigned the reviewers to this.

Best,
Artem

**Review by marikaner — APPROVED** [review]
Thanks, looks good to me!

**Pull request merged**
